# Generated by Django 4.1.7 on 2023-03-18 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_rename_volume_7d_cryptocurrency_percent_change_7d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='favorite_by',
            field=models.ManyToManyField(null=True, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
