# Generated by Django 4.1.7 on 2023-03-18 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0003_alter_cryptocurrency_favorite_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='favorite_by',
            field=models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
