# Generated by Django 4.1.7 on 2023-03-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_cryptocurrency_favorite_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='circulating_supply',
            field=models.BigIntegerField(),
        ),
    ]
