# Generated by Django 4.1.7 on 2023-03-17 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_cryptocurrency_options"),
    ]

    operations = [
        migrations.DeleteModel(name="Cryptocurrency",),
    ]
